import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#005321",
        "on-error": "#ffffff",
        "background": "#faf8ff",
        "on-secondary-fixed": "#2a1700",
        "tertiary-fixed": "#d8e2ff",
        "on-primary-fixed": "#002109",
        "on-tertiary-fixed": "#001a42",
        "surface-container-high": "#e2e7ff",
        "surface-variant": "#dae2fd",
        "on-background": "#131b2e",
        "on-surface-variant": "#3d4a3d",
        "surface-dim": "#d2d9f4",
        "primary": "#006e2f",
        "secondary-container": "#fea619",
        "secondary": "#855300",
        "outline-variant": "#bccbb9",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#283044",
        "error": "#ba1a1a",
        "on-secondary-container": "#684000",
        "surface-container": "#eaedff",
        "tertiary-container": "#82abff",
        "on-surface": "#131b2e",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#ffddb8",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#653e00",
        "primary-fixed": "#6bff8f",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#faf8ff",
        "surface-container-low": "#f2f3ff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#4ae176",
        "surface": "#faf8ff",
        "on-tertiary-fixed-variant": "#004395",
        "primary-container": "#22c55e",
        "tertiary": "#005ac2",
        "on-primary": "#ffffff",
        "surface-tint": "#006e2f",
        "outline": "#6d7b6c",
        "inverse-primary": "#4ae176",
        "secondary-fixed-dim": "#ffb95f",
        "on-primary-container": "#004b1e",
        "surface-container-highest": "#dae2fd",
        "tertiary-fixed-dim": "#adc6ff",
        "on-tertiary-container": "#003d88",
        "inverse-on-surface": "#eef0ff",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      fontFamily: {
        "headline-xl": ["var(--font-rubik)", "sans-serif"],
        "headline-lg": ["var(--font-rubik)", "sans-serif"],
        "headline-md": ["var(--font-rubik)", "sans-serif"],
        "label-lg": ["var(--font-rubik)", "sans-serif"],
        "label-md": ["var(--font-rubik)", "sans-serif"],
        "label-sm": ["var(--font-rubik)", "sans-serif"],
        "body-lg": ["var(--font-nunito-sans)", "sans-serif"],
        "body-md": ["var(--font-nunito-sans)", "sans-serif"],
        "body-sm": ["var(--font-nunito-sans)", "sans-serif"],
      },
      boxShadow: {
        "subtle": "0 1px 8px rgba(0,0,0,0.04)",
        "glow": "0 2px 0 0 #22c55e",
      },
    },
  },
  plugins: [],
};

export default config;
